
name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-and-test:
    runs-on: macos-latest
       
    steps:
      - uses: actions/checkout@v2
      - uses: swift-actions/setup-swift@v1
        with:
              swift-version: "5.6.1"
              xcode-version: latest-stable
      - name: Build and test macOS
        run: xcodebuild clean build test -project EssentialFeedStudy/EssentialDevelopper.xcodeproj -scheme 'CI_macOS' -sdk macosx -destination "platform=macOS" ONLY_ACTIVE_ARCH=YES CODE_SIGN_IDENTITY='' CODE_SIGN_REQUIRED=NO
        
      - name: Build and test iOS
        run: xcodebuild clean build test -project EssentialFeedStudy/EssentialDevelopper.xcodeproj -scheme 'CI_iOS' CODE_SIGN_IDENTITY='' CODE_SIGN_REQUIRED=NO -sdk iphonesimulator -destination "platform=iOS Simulator,OS=15.2,name=iPhone 13 Pro" ONLY_ACTIVE_ARCH=YES
