name: iOS starter workflow

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Build and Test CI scheme using any available iPhone simulator
    runs-on: macos-latest

    steps:
      - name: Test 1
        run: xcodebuild clean build test -project ./../EssentialDevelopper/EssentialDevelopper.xcodeproj -scheme 'CI' CODE_SIGN_IDENTITY='' CODE_SIGN_REQUIRED=NO
          
