
name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-and-test:
    runs-on: macos-latest
       
    steps:
      - uses: swift-actions/setup-swift@v1
        with:
              swift-version: "5.6.1"
              xcode-version: latest-stable
      - name: Build and test
        run: xcodebuild clean build test -project EssentialDevelopper.xcodeproj -scheme 'CI' CODE_SIGN_IDENTITY='' CODE_SIGN_REQUIRED=NO
          
